language: node_js

node_js:
  - v4

before_install:
  - npm install -g grunt-cli
  - ./setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  # for gh-pages
  - git clone --quiet https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git pages
  - cd pages
  - git checkout -b gh-pages origin/gh-pages
  - cd ..

after_success:
  # for gh-pages
  - grunt typedoc:travisCI
  - cd pages
  - ./setup.sh
  - git add .
  - git commit -m "generate typedoc build ${TRAVIS_BUILD_NUMBER} commit:${TRAVIS_COMMIT}"
  - '[ "$TRAVIS_BRANCH" = "master" ] && [ $GH_TOKEN ] && git push --quiet https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages'

notifications:
  email: false

env:
  global:
    # for gh-pages
    - GIT_COMMITTER_NAME=vvakame
    - GIT_COMMITTER_EMAIL=vvakame+dev@gmail.com
    - GIT_AUTHOR_NAME=vvakame
    - GIT_AUTHOR_EMAIL=vvakame+dev@gmail.com
    - secure: fwAb1aeh9MZ32/uEiKDxrP534BEhLA79AI3/jzwrMD7vHobmECUn7RNv5SmyhbkbC3Svvd8B7GcJkebDXZIdO3Gd9N6xcAQn2zAhkmO/ZHu92OZlq+kGwmxcCl3ZBen8JJcIoE8ZF+RBjakf3GNZWHaT+7EJHDfUmsxuJlrC5uQ=
