language: node_js

sudo: false

node_js:
  - v10

before_install:
  - ./setup.sh

notifications:
  email: false

env:
  global:
    # for gh-pages
    - GIT_COMMITTER_NAME=vvakame
    - GIT_COMMITTER_EMAIL=vvakame+dev@gmail.com
    - GIT_AUTHOR_NAME=vvakame
    - GIT_AUTHOR_EMAIL=vvakame+dev@gmail.com
    - secure: fwAb1aeh9MZ32/uEiKDxrP534BEhLA79AI3/jzwrMD7vHobmECUn7RNv5SmyhbkbC3Svvd8B7GcJkebDXZIdO3Gd9N6xcAQn2zAhkmO/ZHu92OZlq+kGwmxcCl3ZBen8JJcIoE8ZF+RBjakf3GNZWHaT+7EJHDfUmsxuJlrC5uQ=
